car/urls.py
from django.contrib import admin
# Add the include function to the import below - import path, "include"
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route localHost:8000
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    # route for cars index
    path('cars/', views.cars_index, name='index'),
    # cars details (show page)
    path('cars/<int:car_id>/', views.cars_detail, name='detail'),
    path('cars/create', views.CarCreate.as_view(), name='cars_create'),
     # CBV expect the params to be int:pk (primary key) "The convention name"
    path('cars/<int:pk>/update/', views.CarUpdate.as_view(), name='cars_update'),
    path('cars/<int:pk>/delete/', views.CarDelete.as_view(), name='cars_delete'),
    path('cars/<int:car_id>/add_filling/', views.add_filling, name='add_filling'),
    path('cars/<int:car_id>/add_photo/', views.add_photo, name='add_photo'),
    path('cars/<int:car_id>/assoc_accs/<int:accs_id>/', views.assoc_accs, name='assoc_accs'),
    path('accss/', views.AccsList.as_view(), name='accss_index'),
    path('accss/<int:pk>/', views.AccsDetail.as_view(), name='accss_detail'),
    path('accss/create/', views.AccsCreate.as_view(), name='accss_create'),
    path('accss/<int:pk>/update/', views.AccsUpdate.as_view(), name='accss_update'),
    path('accss/<int:pk>/delete/', views.AccsDelete.as_view(), name='accss_delete'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse # kinda like redirect
from datetime import date

# Create your models here.
class Accs(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('accss_detail', kwargs={'pk': self.id})


class Car(models.Model):
    make = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    year = models.IntegerField()
    link = models.URLField(max_length=300, default="Enter Car URL Here")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    accss = models.ManyToManyField(Accs)

    def filled_for_week(self):
        return self.filling_set.filter(date=date.today()).count() >= len(FILLS)


    # this function happens when our create form is submitted,
    # and CarsCreate CBV after it has handled the post request
    def get_absolute_url(self):
        # path('car/int:car_id>/'), views.cars_detail, name='detail'),
        # self.id is referring to the car that was just created when you submit the form
        return reverse('detail', kwargs={'car_id': self.id})
    
    def __str__(self):
        return f"{self.make}"
    
class Photo(models.Model):
    url = models.CharField(max_length=200)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for car_id: {self.car_id} @{self.url}"

    

FILLS = (
    ('M', 'Morning'),
    ('A', 'Afternoon'),
    ('N', 'Night'),
)
# select menu ^

# One Car has Many Fillings, a Filling Belongs to a Car
class Filling(models.Model):
    date = models.DateField('Filling Date')
    fill = models.CharField(max_length=1, choices=FILLS, default=FILLS[0][0])
    car = models.ForeignKey(Car, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_fill_display()} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Filling 

class FillingForm(ModelForm):
	class Meta:
		model = Filling 
		fields = ['date', 'fill']

main_app/views.py
# Create your views here.
from django.shortcuts import render, redirect

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

# Add the following import
from django.http import HttpResponse

import uuid
import boto3
from .models import Car, Accs, Photo
from botocore.exceptions import ClientError

from .forms import FillingForm

BUCKET = 'carcollector-sei'
S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'


def add_photo(request, car_id):
	# photo-file will be the "name" attribute on the <input name='photo-file' type='file'>
	photo_file = request.FILES.get('photo-file', None)
	if photo_file:
		# setup the aws client 
		s3 = boto3.client('s3')
		# Make a unique name to store the photo			# franklin.png
														# photo_file.name.rfind('.'): this gets us the file exstension .png
			 # store the file in a catcollector folder/randomnumber + the file name with the extension
		key = 'car/' + uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
		try:
			s3.upload_fileobj(photo_file, BUCKET, key)
			# build the url string of where it is hosted to store db
			url = f"{S3_BASE_URL}{BUCKET}/{key}"
			# add it to the db
			Photo.objects.create(url=url, car_id=car_id)
		except ClientError as e:
			print(e, " error from aws!")
		
	return redirect('detail', car_id=car_id)




# the arguments for the commands comes from our urls.py
# 'cars/<int:car_id>/assoc_accs/<int:accs_id>/'
def assoc_accs(request, car_id, accs_id):
	Car.objects.get(id=car_id).accss.add(accs_id)

	# One line version of below^
	# car + Car.objects.get(id=car_id)
	# car.accss.add(accs_id)
	return redirect('detail', car_id=car_id)

# car_id matches the url
# path('cars/<int:car_id>/add_filling/' 
def add_filling(request, car_id):
	# create a modelForm instance using the information from the post request
	# request.POST is like req.body
	form = FillingForm(request.POST)
	# validate the form
	if form.is_valid():
		# don't want to save it until we add the car_id to the feeding
		new_filling = form.save(commit=False)
		# tying the car to the filling
		# defining the FK
		new_filling.car_id = car_id
		new_filling.save()
		# import redirect on the top line from django.shortcuts
	return redirect('detail', car_id=car_id)

class CarCreate(CreateView):
	model = Car
	fields = ['make', 'color', 'model', 'year']
	def form_valid(self, form):
		form.instance.user = self.request.user
		return super().form_valid(form)


class CarUpdate(UpdateView):
	model = Car
	# disallow the make as input on the form, so no one can update the make
	fields = ['make', 'color', 'model', 'year', 'link']
	
class CarDelete(DeleteView):
	model = Car
	success_url = '/cars' # <- since we can't redirect to a detail page of a car we deleted



def cars_index(request):
  cars = Car.objects.all() # finding all the cars from the db
  return render(request, 'cars/index.html', {'cars': cars})# <- the blue one

# class Car:  # Note that parens are optional if not inheriting from another class
#   def __init__(self, make, color, model, year):
#     self.make = make
#     self.color = color
#     self.model = model
#     self.year = year

# cars = [ # this cars points to below where {'cars': cars}... the blue one
#   Car('Camaro', 'racing yellow', 'R/S Zl1', 1969),
#   Car('Torino', 'supersonic red', '429 Cobra Jet', 1971),
#   Car('Aston Martin', 'Silver Birch', 'DB5', 1964)
# ]

def cars_detail(request, car_id):
   car = Car.objects.get(id=car_id)
   # creating a form (instance) from my FillingForm class
   accss_car_doesnt_have = Accs.objects.exclude(id__in = car.accss.all().values_list('id'))

   filling_form = FillingForm()
   return render(request, 'cars/detail.html', {
	   'car': car, 
	   'filling_form': filling_form,
	   'accss': accss_car_doesnt_have
	   })


# Define the home view
# def home(request):
#   return render(request, 'cars/index.html', { 'cars': car })


def about(request):
    # django is configured to know automatically
    # to look inside of a template's folder for the html files
    return render(request, 'about.html')

class AccsList(ListView):
	model = Accs

class AccsDetail(DetailView):
	model = Accs

class AccsCreate(CreateView):
	model = Accs
	fields = '__all__'

class AccsUpdate(UpdateView):
	model = Accs
	fields = ['name', 'color']

class AccsDelete(DeleteView):
	model = Accs
	success_url = '/accss/'

main_app/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Car Collector</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
    <h1 class="index-title indigo accent-1">About the Car Collector</h1>
    <hr />
    <p class="index-title">Hire the Car Collector!</p>
    <div class="about-img-div">
    <img class="about-img" src="https://media.architecturaldigest.com/photos/56c3aa3a0566de906397280a/4:3/w_3372,h_2529,c_limit/Classic-Car-Collecting-03.jpg" alt="class-car-garage">
    </div>
    {% endblock %}
    <footer>All Rights Reserved, &copy; 2023 Car Collector</footer>
</body>
</html>

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Car Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper indigo accent-1">
        <ul>
          <li><a href="/" class="left brand-logo text center-align">&nbsp;&nbsp;CarCollector</a></li>
        </ul>
        <ul class="right">
					<li><a href="{% url 'about' %}">About</a></li>
					<!-- user is automatically injected by django in every single template -->
					{% if user.is_authenticated %}
    				<li><a href="{% url 'accss_create' %}">Add an Accessory</a></li>
   					<li><a href="{% url 'accss_index' %}">View All Accessories</a></li>
    				<li><a href="{% url 'cars_create' %}">Add a Car</a></li>
    				<li><a href="{% url 'index' %}">View All My Cars</a></li>
    				<li><a href="{% url 'logout' %}">Log Out</a></li>
  					{% else %}
    				<li><a href="{% url 'login' %}">Log In</a></li>
  					{% endif %}
				</ul>
      </div>
    </nav>
  </header>
  <main class="container row">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2023 Car Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/cars/detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<h1 class="index-title indigo accent-1">Car Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ car.make }}</span><img class="responsive-img" src="{{car.link}}" alt=""/>
        <p>Color: {{ car.color }}</p>
        <p>Model: {{ car.model }}</p>
        {% if 1980 > car.year %}
        <p>Year: {{ car.year }} Classic</p>
        {% else %}
        <p>Year: New</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'cars_update' car.id%}">Edit</a>
        <a href="{% url 'cars_delete' car.id%}">Delete</a>
      </div>
    </div>
    {% for photo in car.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
    <div class="card-panel indigo accent-1 center-align">No Photos Uploaded</div>
    {% endfor %}

    <form action="{% url 'add_photo' car.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn" value="Upload Photo">
    </form>
  </div>

  <div class="col s6">
    <form action="{% url 'add_filling' car.id %}" method="POST">
		{% csrf_token %}
		{{ filling_form.as_p }}
		<input type="submit" class="btn" value="Add Fuel">
	</form>
  <br>
  {% if car.filled_for_week %}
    <div class="card-panel indigo accent-1 center-align">{{car.make}} fueled for the week</div>
  {% else %}
    <div class="card-panel red-text center-align">{{car.make}} might need a re-fuel...</div>
  {% endif %}
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Time of Day</th></tr>
      </thead>
      <tbody>
        {% for filling in car.filling_set.all %}
          <tr>
            <td>{{filling.date}}</td>
            <td>{{filling.get_fill_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ car.make }}'s Accessories</h3>
    {% if car.accss.count %}
      {% for accs in car.accss.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ accs.color }}">{{ accs.color }}</span> {{ accs.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Accessories :(</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
    <h3>Available Accessories</h3>
    {% if accss.count %}
      {% for accs in accss.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ accs.color }}">{{ accs.color }}</span> {{ accs.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_accs' car.id accs.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{car.make}} Already Has All Accessories Available</h5>
    {% endif %}
  </div>
</div>

<script>

	const dateEl = document.querySelector('#id_date');
	M.Datepicker.init(dateEl, {
		format: 'yyyy-mm-dd', // this how django formats the date in the model
		defaultDate: new Date(),
		setDefaultDate: true, 
		autoClose: true
	})

	const selectEl = document.querySelector('#id_fill');
	M.FormSelect.init(selectEl)

</script>


{% endblock %}

main_app/templates/cars/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<h1 class="index-title indigo accent-1">The Car Collection</h1>

{% for car in cars %}
<div class="card">
<div class="card-div">
  <a href="{% url 'detail' car.id %}">
  <div class="card col s8">
    <div class="card-content imgdiv">
      <span class="card-title">{{ car.make }}</span><img class="responsive-img" src="{{car.link}}" alt=""/>
      <p>Color: {{ car.color }}</p>
      <p>Model: {{ car.model }}</p>
      {% if 1980 > car.year %}
        <p>Year: {{ car.year }} Classic</p>
      {% else %}
        <p>Year: New</p>
      {% endif %}
    </div>
  </div>
  </a>
</div>
</div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/accs_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Accessory</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'accss_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/accs_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Accessory Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ accs.name }}</span>
        <p>Color: {{ accs.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'accss_update' accs.id %}">Edit</a>
        <a href="{% url 'accss_delete' accs.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/accs_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Accessory</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
	<!-- Django requires the following for security purposes -->
	{% csrf_token %}
	<table>
		<!-- Render the inputs inside of <tr>s & <td>s -->
		{{ form.as_table }}
	</table>
	<input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/accs_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Accessory List</h1>

{% for accs in accs_list %}
  <a href="{% url 'accss_detail' accs.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ accs.name }}</span>
            <p>Color: {{ accs.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/car_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Car</h1>
<!-- object, is the car you are trying to delete -->
  <h4>Are you sure you want to delete <span class="teal-text">{{ object.make }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' car.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/car_form.html
{% extends 'base.html' %}


{% block content %}

<!-- if we are creating a Car, object will be undefined
if we are updateing a Car, the object will be the Car we are udating -->
<!-- object comes from the CarUpdate CBV view -->

{% if object %}
    <h1>Edit <span class="teal-text">{{object.make}}</span></h1>
{% else %}
    <h1>Add A Car!</h1>
{% endif %}



<!-- Leave the action empty makes the form post to the same url 
as what is used to display cars/create -->

<form action="" method="POST">
	<!-- security purpose we include 
	csrf token, cross site request forgery token, protects our forms -->
	{% csrf_token %}
	<table>
		<!-- we get a form variable that is from our CBV CarCreate -->
		{{ form.as_table}}
	</table>
<button type="submit" class="btn">Add Car</button>
</form>
	
{% endblock content %}